### ISSUE TITLE
Sortable not working?

### ISSUE THREAD

**Issue by vnenkpet** [rixxi/gedmo#11]
This is my test entity:

```
<?php

namespace App\Model\Entity;

use Doctrine\Orm\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Sortable\Sortable;
use Kdyby\Doctrine\Entities\Attributes\Identifier;

/**
 * Class TestEntity
 * @ORM\Entity
 * @package App\Model\Entity
 */
final class TestEntity implements Sortable
{
    use Identifier;
    use BlameableEntity;

    /**
     * @var int
     * @ORM\Column(type="integer")
     * @Gedmo\SortablePosition
     */
    private $position;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createDate;
}
```

And in my config:

```
gedmo:
	sortable: on
	timestampable: on
	blameable: on
```

And my little test:
```
	function testSortable()
	{
		$test1 = new TestEntity();
		$this->em->persist($test1);
		$test2 = new TestEntity();
		$this->em->persist($test2);

		$this->em;
		$this->em->flush();

		$entities = $this->em->getRepository(TestEntity::class)->findAll();

		$this->em->remove($entities);
		$this->em->flush();
	}
```

I tried changing various config switchers to see where the problem is, and everything seems OK except that the `sortable` service is simply ignored and the position column works as an ordinary integer column only. Both `blameable` and `timestampable` behaviors work as expected.

What's more, the `gedmo.gedmo.sortable` service doesn't seem to be loaded in the DI container at all (checked with xdebug), while the `gedmo.gedmo.treeable` service is even when I turn it off explicitly in the config with `tree: off`.

**Comment by vnenkpet** [comment]
Just noticed that it works as expected after adding
```
	sortable:
		class: Gedmo\Sortable\SortableListener
		setup:
			- setAnnotationReader(@Doctrine\Common\Annotations\Reader)
		tags: [kdyby.subscriber]
		autowired: no
```

into `vendor/rixxi/gedmo/src/Rixxi/Gedmo/DI/config/gedmo.neon` directly. Why isn't it there by default? Is there anything I'm missing here? The same goes for uploadable I suspect.

**Comment by mishak87** [comment]
Hi you are right, they are missing from config.
Probably because I have not tested or used it and with some listeners were issues so I haven't added them.

**Comment by mishak87** [comment]
If you could test and confirm uploadable is working as expected I will add it.

**Comment by mishak87** [comment]
Thanks for using this lib. After you confirm it works as expected I will merge and release.

**Comment by mishak87** [comment]
Won't fix `uploadable` for now because of lack of testing and demand for it.
