### ISSUE TITLE
Version 1.0.4 breaks Tree Listener

### ISSUE THREAD

**Issue by sasule** [rixxi/gedmo#14]
Hello, 

after updating this repo to version 1.0.4 and updated config directive "tree" to "treeable" I get this Error:
```
The metadata path expects to be an existing directory, I:\www\artbe\vendor\gedmo\doctrine-extensions\lib\Gedmo/Treeable/Entity given.
```
That means config directive is mapped to class however that class does not really exist.

My very ugly hotfix:
OrmExtension.php, line 57
```
foreach ($annotations as $annotation) {
	if ($config['all'] || $config[$annotation]) {
		if ($annotation === 'treeable'){
			$annotation = 'tree';
		}
		$name = ucfirst($annotation);
		$mappings["Gedmo\\$name\\Entity"] = "$path/$name/Entity"; //this line produces reported error
	}
}
```
Maybe some kind of remapping annotation to class would be the solution.

Should I make a pull request? 

Best regards,
Saša

**Comment by mishak87** [comment]
Hi Saša,
I apologize for that it was not really necessary for me to release it and it seems like it was a hasty decision.
Please make pull request if you can.

**Comment by sasule** [comment]
Nevermind, bad things happen.

Pull request sent.

**Comment by mishak87** [comment]
Thanks for pull I decided to fix it myself. Please have a look at #16

**Comment by mishak87** [comment]
Please check the release 1.0.5 and close the issue if it works!
Thank you for fast cooperation :-) !

**Comment by sasule** [comment]
Yep, works fine, closing the issue.

My thanks belog to you too :-)
